"""Reviewed public book pages that provide exact-edition evidence."""

from dataclasses import dataclass
from typing import Literal

from data_pipeline.identifiers import stable_id


@dataclass(frozen=True)
class PublicBookSourceSpec:
    """Identity and completeness checks for one public catalog page."""

    slug: str
    provider: str
    topic: str
    book_id: str
    isbn_13: str
    title: str
    edition: int
    url: str
    toc_format: Literal[
        "indented_table",
        "indented_table_chapter_roots",
        "heading_sequence",
        "flat_bold",
        "flat_table",
        "paragraph_sequence",
        "bold_chapter_paragraphs",
    ]
    expected_toc_count: int
    expected_root_titles: tuple[str, ...]
    expected_chapter_labels: tuple[str, ...]
    expected_child_label_groups: tuple[tuple[str, ...], ...] = ()
    expected_child_counts: tuple[int, ...] = ()
    expected_descendant_counts: tuple[int, ...] = ()
    preferred_toc: bool = False


PUBLIC_BOOK_SOURCES = {
    "ecampus-osc10": PublicBookSourceSpec(
        slug="ecampus-osc10",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9781119800361",
        isbn_13="9781119800361",
        title="Operating System Concepts",
        edition=10,
        url="https://umass.ecampus.com/operating-system-concepts-10th/bk/9781119800361",
        toc_format="paragraph_sequence",
        expected_toc_count=36,
        expected_root_titles=(
            "Overview",
            "Process Management",
            "Process Synchronization",
            "Memory Management",
            "Storage Management",
            "File System",
            "Security and Protection",
            "Advanced Topics",
            "Case Studies",
            "Appendices",
        ),
        expected_chapter_labels=(
            *(str(number) for number in range(1, 22)),
            "A",
            "B",
            "C",
            "D",
            "E",
        ),
        expected_child_label_groups=(
            ("1", "2"),
            ("3", "4", "5"),
            ("6", "7", "8"),
            ("9", "10"),
            ("11", "12"),
            ("13", "14", "15"),
            ("16", "17"),
            ("18", "19"),
            ("20", "21"),
            ("A", "B", "C", "D", "E"),
        ),
    ),
    "ecampus-osc-essentials2": PublicBookSourceSpec(
        slug="ecampus-osc-essentials2",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9781118804926",
        isbn_13="9781118804926",
        title="Operating System Concepts Essentials",
        edition=2,
        url=(
            "https://centralmethodist.ecampus.com/"
            "operating-system-concepts-essentials-2nd/bk/9781118804926"
        ),
        toc_format="paragraph_sequence",
        expected_toc_count=22,
        expected_root_titles=(
            "OVERVIEW.",
            "PROCESS MANAGEMENT.",
            "MEMORY MANAGEMENT.",
            "STORAGE MANAGEMENT.",
            "PROTECTION AND SECURITY.",
            "CASE STUDIES.",
            "APPENDICES.",
        ),
        expected_chapter_labels=tuple(str(number) for number in range(1, 16)),
        expected_child_label_groups=(
            ("1", "2"),
            ("3", "4", "5", "6"),
            ("7", "8"),
            ("9", "10", "11", "12"),
            ("13", "14"),
            ("15",),
            (),
        ),
        expected_child_counts=(2, 4, 2, 4, 2, 1, 0),
        preferred_toc=True,
    ),
    "ecampus-anton-linear-algebra10": PublicBookSourceSpec(
        slug="ecampus-anton-linear-algebra10",
        provider="ecampus",
        topic="linear-algebra",
        book_id="isbn13:9780470458211",
        isbn_13="9780470458211",
        title="Elementary Linear Algebra, 10th Edition",
        edition=10,
        url=("https://drake.ecampus.com/elementary-linear-algebra-10th-edition/bk/9780470458211"),
        toc_format="flat_table",
        expected_toc_count=64,
        expected_root_titles=(
            "Systems Of Linear Equations And Matrices",
            "Introduction to Systems of Linear Equations",
            "Gaussian Elimination",
            "Matrices and Matrix Operations",
            "Inverses Algebraic Properties of Matrices",
            "Elementary Matrices and a Method for Finding A-1",
            "More on Linear Systems and Invertible Matrices",
            "Diagonal, Triangular, and Symmetric Matrices",
            "Applications of Linear Systems (Traffic flow Electrical Networks Balancing "
            "Chemical Equations, Polynomial Interpolation)",
            "Leontief Input-Output Models * Chapter Summary",
            "Determinants",
            "Determinants by Cofactor Expansion",
            "Evaluating Determinants by Row Reduction",
            "Properties of Determinants Adjoint Cramer's Rule * Chapter Summary",
            "Euclidean Vector Spaces",
            "Vectors in 2-space, 3-space, and n-space",
            "Norm, Dot Product, and Distance in Rn",
            "Orthogonality",
            "The Geometry of Linear Systems",
            "Cross Product * Chapter Summary",
            "General Vector Spaces",
            "Real Vector Spaces",
            "Subspaces",
            "Linear Independence",
            "Coordinates and Basis",
            "Dimension",
            "Change of Basis",
            "Row Space, Column Space, and Null Space",
            "Rank, Nullity, and the Fundamental Matrix Spaces",
            "Linear Transformations from Rn to Rm",
            "Properties of Matrix Transformations from Rn to Rm",
            "Geometry of Matrix Operators",
            "Dynamical Systems and Markov Chains * Chapter Summary",
            "Eignvalues And Eigenvectors",
            "Eigenvalues and Eigenvectors",
            "Diagonalization",
            "Complex Vector Spaces",
            "Application to Differential Equations * Chapter Summary",
            "Inner Product Spaces",
            "Inner Products",
            "Angle and Orthogonality in Inner Product Spaces",
            "Orthonormal Bases Gram-Schmidt Process QR - Decomposition",
            "Best Approximation Least Squares",
            "Least Squares Fitting to Data",
            "Fourier Series * Chapter Summary",
            "Diagonalization And Quadratic Forms",
            "Orthogonal Matrices",
            "Orthogonal Diagonalization",
            "Quadratic Forms",
            "Application of Quadratic Forms to Optimization",
            "Hermitian, Unitary, and Normal Matrices * Chapter Summary",
            "Linear Transformations",
            "General Linear Transformations",
            "Isomorphism",
            "Composition and Inverse Transformations",
            "Matrices of General Linear Transformations",
            "Similarity * Chapter Summary",
            "Numerical Methods",
            "Matrix Factorization and LU-Decompositions",
            "The Power Method",
            "Application to Internet Search Engines",
            "Comparison of Procedures for Solving Linear Systems",
            "Singular-Value Decomposition",
            "Application of Singular Value Decomposition to Data Compression * Chapter Summary",
        ),
        expected_chapter_labels=(),
        preferred_toc=True,
    ),
    "ecampus-penney-linear-algebra4": PublicBookSourceSpec(
        slug="ecampus-penney-linear-algebra4",
        provider="ecampus",
        topic="linear-algebra",
        book_id="isbn13:9781118909584",
        isbn_13="9781118909584",
        title="Linear Algebra Ideas and Applications",
        edition=4,
        url=("https://wright.ecampus.com/linear-algebra-ideas-applications-4th/bk/9781118909584"),
        toc_format="bold_chapter_paragraphs",
        expected_toc_count=161,
        expected_root_titles=(
            "Preface",
            "Features of the Text",
            "Acknowledgments",
            "About the Companion Website",
            "Systems of Linear Equations",
            "Linear Independence and Dimension",
            "Linear Transformations",
            "Determinants",
            "Eigenvectors and Eigenvalues",
            "Orthogonality",
            "Generalized Eigenvectors",
            "Numerical Techniques",
            "Answers and Hints",
            "Index",
        ),
        expected_chapter_labels=tuple(str(number) for number in range(1, 9)),
        expected_child_label_groups=(
            (),
            (),
            (),
            (),
            (
                "1.1",
                "1.1.1",
                "1.1.2",
                "1.2",
                "1.2.1",
                "1.2.2",
                "1.3",
                "1.3.1",
                "1.3.2",
                "1.4",
                "1.4.1",
            ),
            ("2.1", "2.1.1", "2.2", "2.2.1", "2.2.2", "2.3", "2.3.1"),
            (
                "3.1",
                "3.1.1",
                "3.2",
                "3.2.1",
                "3.2.2",
                "3.3",
                "3.3.1",
                "3.3.2",
                "3.4",
                "3.4.1",
                "3.5",
                "3.5.1",
            ),
            ("4.1", "4.1.1", "4.1.2", "4.2", "4.2.1", "4.3"),
            ("5.1", "5.1.1", "5.1.2", "5.2", "5.2.1", "5.2.2", "5.3", "5.3.1"),
            (
                "6.1",
                "6.2",
                "6.2.1",
                "6.3",
                "6.3.1",
                "6.3.2",
                "6.4",
                "6.4.1",
                "6.5",
                "6.5.1",
                "6.6",
                "6.6.1",
                "6.7",
                "6.8",
            ),
            ("7.1", "7.2"),
            ("8.1", "8.2"),
            (),
            (),
        ),
        expected_child_counts=(0, 0, 0, 0, 26, 16, 26, 12, 16, 34, 7, 10, 0, 0),
    ),
    "ecampus-larson-linear-algebra5": PublicBookSourceSpec(
        slug="ecampus-larson-linear-algebra5",
        provider="ecampus",
        topic="linear-algebra",
        book_id="isbn13:9780618335671",
        isbn_13="9780618335671",
        title="Elementary Linear Algebra",
        edition=5,
        url=(
            "https://cincinnatistate.ecampus.com/"
            "elementary-linear-algebra-5th-larson-ron/bk/9780618335671"
        ),
        toc_format="flat_table",
        expected_toc_count=65,
        expected_root_titles=(
            "Note: Each chapter concludes with a Chapter Summary, Review Exercises, and "
            "Projects. What Is Linear Algebra?",
            "Systems of Linear Equations Biographical Sketch of Carl Friedrich Gauss",
            "Introduction to Systems of Linear Equations",
            "Gaussian Elimination and Gauss-Jordan Elimination",
            "Applications of Systems of Linear Equations",
            "Matrices Biographical Sketch of Arthur Cayley",
            "Operations with Matrices",
            "Properties of Matrix Operations",
            "The Inverse of a Matrix",
            "Elementary Matrices",
            "Applications of Matrix Operations",
            "Determinants Biographical Sketch of Augustin-Louis Cauchy",
            "The Determinant of a Matrix",
            "Evaluation of a Determinant Using Elementary Operations",
            "Properties of Determinants",
            "Introduction to Eigenvalues",
            "Applications of Determinants Cumulative Test for Chapters 1–3",
            "Vector Spaces Biographical Sketch of William Rowan Hamilton",
            "Vectors in Rn",
            "Vector Spaces",
            "Subspaces of Vector Spaces",
            "Spanning Sets and Linear Independence",
            "Basis and Dimension",
            "Rank of a Matrix and Systems of Linear Equations",
            "Coordinates and Change of Basis",
            "Applications of Vector Spaces",
            "Inner Product Spaces Biographical Sketch of Jean-Baptiste Joseph Fourier",
            "Length and Dot Product in Rn",
            "Inner Product Spaces",
            "Orthonormal Bases: Gram-Schmidt Process",
            "Mathematical Models and Least Squares Analysis",
            "Applications of Inner Product Spaces Cumulative Test for Chapters 4 and 5",
            "Linear Transformations Biographical Sketch of Emmy Noether",
            "Introduction to Linear Transformations",
            "The Kernel and Range of a Linear Transformation",
            "Matrices for Linear Transformations",
            "Transition Matrices and Similarity",
            "Applications of Linear Transformations",
            "Eigenvalues and Eigenvectors Biographical Sketch of James Joseph Sylvester",
            "Eigenvalues and Eigenvectors",
            "Diagonalization",
            "Symmetric Matrices and Orthogonal Diagonalization",
            "Applications of Eigenvalues and Eigenvectors Cumulative Test for Chapters 6 and 7",
            "Complex Vector Spaces* Biographical Sketch of Charles Hermite",
            "Complex Numbers",
            "Conjugates and Division of Complex Numbers",
            "Polar Form and DeMoivre's Theorem",
            "Complex Vector Spaces and Inner Products",
            "Unitary and Hermitian Matrices",
            "Linear Programming* Biographical Sketch of John von Neumann",
            "Systems of Linear Inequalities",
            "Linear Programming Involving Two Variables",
            "The Simplex Method: Maximization",
            "The Simplex Method: Minimization",
            "The Simplex Method: Mixed Constraints",
            "Numerical Methods",
            "Biographical Sketch of Carl Gustav Jacob Jacobi",
            "Gaussian Elimination with Partial Pivoting",
            "Interative Methods for Solving Linear Systems",
            "Power Method for Approximating Eigenvalues",
            "Applications of Numerical Methods",
            "Appendices",
            "Mathematical Induction and Other Forms of Proofs",
            "Computer Algebra Systems and Graphing Calculators",
            "Answer Key Index * Chapters 8, 9, and 10 are available on the Learning Tools "
            "Student CD-ROM and the textbook web site",
        ),
        expected_chapter_labels=(),
    ),
    "ecampus-nutt-os3": PublicBookSourceSpec(
        slug="ecampus-nutt-os3",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9780201741964",
        isbn_13="9780201741964",
        title="Operating Systems: A Modern Perspective",
        edition=3,
        url=(
            "https://campusstore.miamioh.edu/"
            "operating-systems-modern-perspective-3rd/bk/9780201741964"
        ),
        toc_format="indented_table_chapter_roots",
        expected_toc_count=429,
        expected_root_titles=(
            "Preface",
            "To the Student",
            "To the Instructor",
            "Introduction",
            "Using the Operating System",
            "Operating System Organization",
            "Computer Organization",
            "Device Management",
            "Process Management",
            "Scheduling",
            "Basic Synchronization Principles",
            "High-Level Synchronization",
            "Deadlock",
            "Memory Management",
            "Virtual Memory",
            "File Management",
            "Protection and Security",
            "Networks",
            "Remote Files",
            "Distributed Computing",
            "Strategies and Examples",
            "Glossary",
            "Bibliography",
            "Index",
        ),
        expected_chapter_labels=(),
        expected_child_counts=(
            0,
            0,
            0,
            4,
            7,
            5,
            8,
            6,
            8,
            6,
            6,
            6,
            7,
            6,
            7,
            8,
            7,
            8,
            7,
            6,
            10,
            0,
            0,
            0,
        ),
        expected_descendant_counts=(
            0,
            0,
            0,
            19,
            22,
            19,
            19,
            24,
            20,
            20,
            15,
            23,
            21,
            21,
            25,
            31,
            20,
            29,
            22,
            20,
            35,
            0,
            0,
            0,
        ),
    ),
    "ecampus-tanenbaum-distributed1": PublicBookSourceSpec(
        slug="ecampus-tanenbaum-distributed1",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9780132199087",
        isbn_13="9780132199087",
        title="Distributed Operating Systems",
        edition=1,
        url="https://cincinnatistate.ecampus.com/distributed-operating-systems-1st/bk/9780132199087",
        toc_format="flat_bold",
        expected_toc_count=12,
        expected_root_titles=(
            "Preface.",
            "Introduction to Distributed Systems.",
            "Communication in Distributed Systems.",
            "Synchronization in Distributed Systems.",
            "Processes and Processors in Distributed Systems.",
            "Distributed File Systems.",
            "Distributed Shared Memory.",
            "Case Study I: Amoeba.",
            "Case Study II: Mach.",
            "Case Study III: Chorus.",
            "Case Study IV: DCE.",
            "Index.",
        ),
        expected_chapter_labels=tuple(str(number) for number in range(1, 11)),
    ),
    "ecampus-bach-unix1": PublicBookSourceSpec(
        slug="ecampus-bach-unix1",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9780132017992",
        isbn_13="9780132017992",
        title="Design of the UNIX Operating System",
        edition=1,
        url="https://wright.ecampus.com/design-unix-operating-system-1st-bach/bk/9780132017992",
        toc_format="flat_bold",
        expected_toc_count=12,
        expected_root_titles=(
            "General Review of the System.",
            "Introduction to the Kernel.",
            "The Buffer Cache.",
            "Internal Representation of Files.",
            "System Calls for the File System.",
            "The System Representation of Processes.",
            "Process Control.",
            "Process Scheduling and Time.",
            "Memory Management Policies.",
            "Interprocess Communication.",
            "Multiprocessor Systems.",
            "Distributed UNIX System.",
        ),
        expected_chapter_labels=tuple(str(number) for number in range(1, 13)),
    ),
    "ecampus-stallings-os4": PublicBookSourceSpec(
        slug="ecampus-stallings-os4",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9780130319999",
        isbn_13="9780130319999",
        title="Operating Systems: Internals and Design Principles",
        edition=4,
        url=(
            "https://cincinnatistate.ecampus.com/"
            "operating-systems-internals-design/bk/9780130319999"
        ),
        toc_format="indented_table",
        expected_toc_count=201,
        expected_root_titles=(
            "Web Site for Operating Systems: Internals and Design Principles",
            "Preface",
            "PART ONE BACKGROUND",
            "PART TWO PROCESSES",
            "PART THREE MEMORY",
            "PART FOUR SCHEDULING",
            "PART FIVE INPUT/OUTPUT AND FILES",
            "PART SIX DISTRIBUTED SYSTEMS",
            "PART SEVEN SECURITY",
            "APPENDICES",
            "Glossary",
            "References",
            "Index",
        ),
        expected_chapter_labels=(),
    ),
    "ecampus-singhal-os1": PublicBookSourceSpec(
        slug="ecampus-singhal-os1",
        provider="ecampus",
        topic="operating-systems",
        book_id="isbn13:9780070575721",
        isbn_13="9780070575721",
        title="Advanced Concepts In Operating Systems",
        edition=1,
        url=(
            "https://cincinnatistate.ecampus.com/"
            "advanced-concepts-operating-systems-1st/bk/9780070575721"
        ),
        toc_format="heading_sequence",
        expected_toc_count=27,
        expected_root_titles=(
            "Process Synchronization",
            "Distributed Operating Systems",
            "Distributed Resource Management",
            "Failure Recovery and Fault Tolerance",
            "Protection and Security",
            "Multiprocessor Operating Systems",
            "Database Operating Systems",
        ),
        expected_chapter_labels=tuple(str(number) for number in range(1, 21)),
    ),
}


def public_book_source(source_slug: str) -> PublicBookSourceSpec:
    """Return one reviewed source or reject arbitrary public pages."""
    try:
        return PUBLIC_BOOK_SOURCES[source_slug]
    except KeyError as exc:
        choices = ", ".join(sorted(PUBLIC_BOOK_SOURCES))
        raise ValueError(f"public book source must be one of: {choices}") from exc


def public_book_source_id(source_spec: PublicBookSourceSpec) -> str:
    """Return the deterministic canonical source ID for a reviewed catalog page."""
    return stable_id("source", source_spec.provider, source_spec.url, source_spec.book_id)


def preferred_public_toc_source_ids() -> dict[str, str]:
    """Map each explicitly reviewed replacement book to its preferred TOC source."""
    preferred: dict[str, str] = {}
    for source_spec in PUBLIC_BOOK_SOURCES.values():
        if not source_spec.preferred_toc:
            continue
        if source_spec.book_id in preferred:
            raise ValueError(f"multiple preferred TOC sources configured for {source_spec.book_id}")
        preferred[source_spec.book_id] = public_book_source_id(source_spec)
    return preferred
